### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sahayayush987** [anirudh9784/Major_Project#1]
![Capture](https://user-images.githubusercontent.com/26841143/142054861-60e44ec6-dcef-4215-b6c2-8385dc991edd.PNG)

**Comment by anirudh9784** [comment]
Labels_URL link which is used in this repository is no longer available. Either change the link or directly add a list of labels in code.

**Comment by anirudh9784** [comment]
![image](https://user-images.githubusercontent.com/45981913/142732689-6587c753-1981-4f40-81bf-084ee7485306.png)
